### ISSUE TITLE
nvidia-kmod-common should be kickstart friendly

### ISSUE THREAD

**Issue by derekschrock** [negativo17/nvidia-kmod-common#10]
When performing a kickstart installation `/etc/default/grub` does not exist  during rpm `%post` (or any scriptlet phase?) the [sourcing](https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia-kmod-common.spec#L81) of `/etc/default/grub` in `%post` will fail.  In turn anaconda fails during `%packages`.

anaconda [creates](https://github.com/rhinstaller/anaconda/blob/5f65099411bccc11fd44555dadded55a0808c7bd/pyanaconda/modules/storage/bootloader/grub2.py#L253) `/etc/default/grub` during bootloader installation late in the EL/Fedora installation. and  doesn't consider any existing data r/w truncating the file and wiping away any changes from `nvidia-kmod-common` `%post`

I believe the simple fix here to just make the package kickstartable and to retain current functionality check before sourcing:

```sh
  %post
  ...
  [ -f %{_sysconfdir}/default/grub ] && . %{_sysconfdir}/default/grub
  ...
```

However, that now leaves the question how does `nvidia-kmod-common` update `/etc/default/grub` during a kickstart?  

Any additional updates to nvidia-kmod-commont would change current kernel via `grubby` and `/etc/default/grub` on a running system however I'm guessing we would want that during install too?

Would it make sense to include a new file that's placed in `/etc/grub.d/99_nvidia` that contains the contents of `%post` scriptlet that adds/removes kernel options?

I believe no matter `[ -f ... ] && ...` should be added to allow the package to be installable during a kickstart however I'm open to suggestions on how to best handle this with grub upates.

A possible workaround to get `/etc/default/grub` updated is to recommend the `nvidia-kmod-common` be reinstalled during anaonda `%post` if you're using this package during a kickstart.. I'm not 100% this would work but just trying to guess.   

Or maybe recommend the kickstart use 
  `bootloader ... --append="nouveau.modeset=0 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau"`  
 this doesn't addres the rmmods though.

**Comment by scaronni** [comment]
Interesting issue. We kickstart AlmaLinux and Fedora laptops at work but we've not hit this issue as we do a minimal + FreeIPA install and then adjust the system with Ansible (Nvidia drivers included), so we don't hit this corner case.

> When performing a kickstart installation `/etc/default/grub` does not exist during rpm `%post` (or any scriptlet phase?) the [sourcing](https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia-kmod-common.spec#L81) of `/etc/default/grub` in `%post` will fail. In turn anaconda fails during `%packages`.
> 
> anaconda [creates](https://github.com/rhinstaller/anaconda/blob/5f65099411bccc11fd44555dadded55a0808c7bd/pyanaconda/modules/storage/bootloader/grub2.py#L253) `/etc/default/grub` during bootloader installation late in the EL/Fedora installation. and doesn't consider any existing data r/w truncating the file and wiping away any changes from `nvidia-kmod-common` `%post`
> 
> I believe the simple fix here to just make the package kickstartable and to retain current functionality check before sourcing:
> 
> ```shell
>   %post
>   ...
>   [ -f %{_sysconfdir}/default/grub ] && . %{_sysconfdir}/default/grub
>   ...
> ```


We're already skipping sourcing `/etc/default/grub` when the system is booted with ostree, so maybe I can add your conditional  source to disable it in the case of kickstarts.

> However, that now leaves the question how does `nvidia-kmod-common` update `/etc/default/grub` during a kickstart?
> 
> Any additional updates to nvidia-kmod-commont would change current kernel via `grubby` and `/etc/default/grub` on a running system however I'm guessing we would want that during install too?

Correct, otherwise you will not have a working setup regardless of the fact that you installed the drivers.

> Would it make sense to include a new file that's placed in `/etc/grub.d/99_nvidia` that contains the contents of `%post` scriptlet that adds/removes kernel options?
>
> I believe no matter `[ -f ... ] && ...` should be added to allow the package to be installable during a kickstart however I'm open to suggestions on how to best handle this with grub upates.
> 
> A possible workaround to get `/etc/default/grub` updated is to recommend the `nvidia-kmod-common` be reinstalled during anaonda `%post` if you're using this package during a kickstart.. I'm not 100% this would work but just trying to guess.
> 
> Or maybe recommend the kickstart use `bootloader ... --append="nouveau.modeset=0 rd.driver.blacklist=nouveau modprobe.blacklist=nouveau"` this doesn't addres the rmmods though.

I think files in `/etc/grub.d` go out of context because that is for manipulating the grub file and not the kernel command line entries, but I might be wrong. I will look into it. The other options I think create more confusion than anything else.

I will look what other packages do in this regard.

Thanks for reporting!

**Comment by derekschrock** [comment]
>I think files in /etc/grub.d go out of context because that is for manipulating the grub file and not the kernel command line entries, but I might be wrong.

Yes I believe you're right.  I was thinking grub2-mkconfig sourced the files from `/etc/grub.d`. That's not the case it's executed so even if you got something before 10_linux the context is lost.

Given that `grubby` and updates to `/etc/default/grub` are lost during a kickstart exclude anaconda `%post` would it a `oneshot` service using `ConditionFileExists` or `ConditionFirstBoot` where it auto reboots?

It really seems like anaconda should be reading `/etc/default/grub` for values and not blindly overwrite it.
Maybe not el7 but does [BootLoaderSpec](https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault#Differences_from_BootLoaderSpec) help?

**Comment by scaronni** [comment]
Picking this up again... here is the proposed implementation:

- The `%post` and `%preun` scripts go into a separate script inside the package.
- The `%post` script checks if any bootloader is already configured, otherwise prints a message to call the script manually once a bootloader is configured and exits gracefully.
- The user who is installing the system with kickstart needs to run the script in the last steps after the system is configured.

More details:
```
# /usr/sbin/nvidia-boot-update 
Tool to add or remove kernel command line options required for proper operation of the Nvidia driver.
It is usually called from the %post/%preun scripts of the Nvidia packages, but it can also be used at later stages, for example in a kickstart file after the drivers have been already installed.

Boot loaders supported:
  - grub
  - systemd-boot

Usage: nvidia-update-boot [OPTION...]
    post       Adjust necessary kernel command line options
    preun      Remove all kernel command line options

```

In case of a kickstart install, will print this out:
```
Nvidia driver setup: no bootloader detected. Please run 'nvidia-boot-update post' manually.
```

**Comment by scaronni** [comment]
Proposed solution on the last commit: https://github.com/negativo17/nvidia-kmod-common/commits/master/

**Comment by GloriousEggroll** [comment]
Does the following not work with Anaconda? we use this but we use Calamares installer:

1.
```
#workaround for successful nvidia graphics driver installation
%pre-install
mkdir -p /mnt/sysimage/etc/default
touch /mnt/sysimage/etc/default/grub
%end
```

2.
```
%packages
....
nvidia-driver
akmod-nvidia
nvidia-settings
nvidia-driver-cuda
nvidia-kmod-common
nvidia-driver-libs.i686
nvidia-driver-cuda-libs.i686
nvidia-gpu-firmware
....
%end
```

3.
```
%post
....
# Add nvidia kernel boot options to calamares post install shellprocess commands
echo '    - "echo GRUB_CMDLINE_LINUX=\"rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1\" >> /etc/default/grub"' >> /usr/share/calamares/modules/shellprocess.conf
sed -i "s|GRUB_CMDLINE_LINUX|\'GRUB_CMDLINE_LINUX|g" /usr/share/calamares/modules/shellprocess.conf
sed -i "s| >> /etc/default/grub|\' >> /etc/default/grub|g" /usr/share/calamares/modules/shellprocess.conf

# update grub in calamares post install shellprocess commands
cat << EOF >> /usr/share/calamares/modules/shellprocess.conf
    - command: "/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg"
      timeout: 3600
EOF
....
%end
```

I haven't used Anaconda in a year or so, so I'm not sure if it has any customized post-install shell process you can modify like Calamares does. Either way 1. and 2. are needed to ensure /etc/default/grub exists during installation for the nvidia driver and to wipe /tmp so the kickstart doesnt error out when unmounting it.

**Comment by scaronni** [comment]
@GloriousEggroll yeah exactly, with that script as a `%post` action, you can skip step 1, and in step 3 you just run `nvidia-boot-update post`. Definitely simpler.

**Comment by scaronni** [comment]
I will simplify the script again after christmas, there's plenty of optimizations that can be done and some additions I have to add for `systemd-boot`.

**Comment by scaronni** [comment]
This is pretty ridiculous: https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia-boot-update#L4-L52

**Comment by GloriousEggroll** [comment]
question -- have you considered patching in nvidia-drm.modeset (and 545+ nvidia-drm.fbdev) as enabled by default?

We did that and it prevents having to set them in grub or modprobe, a lot less hassle. We also re-enabled for 535 the rpmfusion patch that kicks other framebuffers off before nvidia takes over -- it prevents the ghost screen

https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/545.29.06/dkms/0001-enable-nvidia-drm.modeset-1-as-default.patch

https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/545.29.06/dkms/0001-enable-nvidia-drm.fbdev-1-as-default.patch

Also, the grub portions of the script had some problems where it would add duplicate GRUB_CMDLINE_LINUX entries and would remove `quiet splash`, and it would also remove GRUB_CMDLINE_LINUX_DEFAULT. I modified that and its working much cleaner here:

https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/545.29.06/kmod-common/nvidia-boot-update

**Comment by scaronni** [comment]
> question -- have you considered patching in nvidia-drm.modeset (and 545+ nvidia-drm.fbdev) as enabled by default?
> 
> We did that and it prevents having to set them in grub or modprobe, a lot less hassle. We also re-enabled for 535 the rpmfusion patch that kicks other framebuffers off before nvidia takes over -- it prevents the ghost screen

You mean this patch here? https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/535.146.02/kmod/0001-simpledrm-nvidia-drm-override.patch

Not available for 545?

> https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/545.29.06/dkms/0001-enable-nvidia-drm.modeset-1-as-default.patch
> 
> https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/545.29.06/dkms/0001-enable-nvidia-drm.fbdev-1-as-default.patch

Interesting take, I'm just not sure if we should deviate from upstream documentation.

> Also, the grub portions of the script had some problems where it would add duplicate GRUB_CMDLINE_LINUX entries and would remove `quiet splash`, and it would also remove GRUB_CMDLINE_LINUX_DEFAULT. I modified that and its working much cleaner here:
> 
> https://github.com/Nobara-Project/rpm-sources/blob/main/appstream/nobara-nvidia-drivers/545.29.06/kmod-common/nvidia-boot-update

Can you please rebase or make a merge request? Btw, "splash" shouldn't be "rhgb"? this is what is usually added by default.

**Comment by scaronni** [comment]
I was checking that repository and noticed you picked up my attempt with a separate package for the open source modules: https://github.com/Nobara-Project/rpm-sources/tree/main/appstream/nobara-nvidia-drivers/545.29.06

I did not go that route in the end: https://negativo17.org/nvidia-proprietary-and-open-source-kernel-modules/

**Comment by scaronni** [comment]
I've pushed the udpate to the repositories. I haven't tested it yet on ostree based systems, but will do in the next days and update accordingly.

The `GRUB_CMDLINE_LINUX_DEFAULT` entries are always added to `GRUB_CMDLINE_LINUX` by `grub2-mkconfig`, even if not documented.
