### ISSUE TITLE
Missing space in 99-nvidia.conf

### ISSUE THREAD

**Issue by roshanshariff** [negativo17/nvidia-kmod-common#8]
https://github.com/negativo17/nvidia-kmod-common/blob/71d5b9605a30fba8e1d902dee36af5d0f39ed11e/99-nvidia.conf#L3

Commit 7140ae5e dropped the space before the closing quotes, which causes `dracut` to produce a warning:
```
/usr/lib/dracut/dracut.conf.d/99-nvidia.conf:omit_drivers+=" nvidia nvidia-drm nvidia-modeset nvidia-peermem nvidia-uvm"

dracut: WARNING: <key>+=" <values> ": <values> should have surrounding white spaces!
dracut: WARNING: This will lead to unwanted side effects! Please fix the configuration file.
```

**Comment by scaronni** [comment]
Ah! Thank you, I just noticed that myself this morning. Uploading 495.44-2 just now.
Thanks!
