### ISSUE TITLE
GRUB_CMDLINE_LINUX empty after uninstall

### ISSUE THREAD

**Issue by kmittman** [negativo17/nvidia-kmod-common#9]
Hi @scaronni 
Received this pull request https://github.com/NVIDIA/yum-packaging-nvidia-kmod-common/pull/1

**Comment by scaronni** [comment]
Hi @kmittman, thanks for letting me know.
My SPEC file already has all the required bits: https://github.com/negativo17/nvidia-kmod-common/blob/master/nvidia-kmod-common.spec#L83

**Comment by scaronni** [comment]
Nevermind, i was reading the wrong line. I applied it. Thanks!
